import { CategoryId } from './storage';

export interface CategoryConfig {
  id: CategoryId;
  label: string;
  shortLabel: string;
  color: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
  lightBg: string;
  icon: string;
  fields: FieldConfig[];
}

export interface FieldConfig {
  key: string;
  label: string;
  type: 'text' | 'date' | 'number' | 'select' | 'tel';
  required?: boolean;
  options?: string[];
  placeholder?: string;
  sensitive?: boolean;
}

export const CATEGORIES: CategoryConfig[] = [
  {
    id: 'password-vault',
    label: 'Passwords',
    shortLabel: 'Passwords',
    color: '#E8B347',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'KeyRound',
    fields: [
      {
        key: 'Website / App',
        label: 'Website / App',
        type: 'text',
        required: true,
        placeholder: 'e.g. Gmail, Instagram, HDFC NetBanking',
      },
      {
        key: 'Login URL',
        label: 'Login URL',
        type: 'text',
        placeholder: 'e.g. https://accounts.google.com',
      },
      {
        key: 'User ID / Email',
        label: 'User ID / Email',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'e.g. name@example.com',
      },
      {
        key: 'Password',
        label: 'Password',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'Saved securely in your vault',
      },
      {
        key: '2FA / Recovery',
        label: '2FA / Recovery notes',
        type: 'text',
        sensitive: true,
        placeholder: 'e.g. backup codes location',
      },
    ],
  },
  {
    id: 'government-ids',
    label: 'Government IDs',
    shortLabel: 'Gov IDs',
    color: '#F1AA9B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'CreditCard',
    fields: [
      {
        key: 'Document Type',
        label: 'Document Type',
        type: 'select',
        required: true,
        options: [
          'Aadhaar Card',
          'PAN Card',
          'Passport',
          'Voter ID',
          'Driving License',
          'Birth Certificate',
          'Other',
        ],
      },
      {
        key: 'ID / Document Number',
        label: 'ID / Document Number',
        type: 'text',
        required: true,
        sensitive: true,
      },
      { key: 'Date of Issue', label: 'Date of Issue', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
      { key: 'Issuing Authority', label: 'Issuing Authority', type: 'text' },
      { key: 'Address on Document', label: 'Address on Document', type: 'text' },
    ],
  },
  {
    id: 'bank-accounts',
    label: 'Bank Accounts',
    shortLabel: 'Bank',
    color: '#8EB4E8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Landmark',
    fields: [
      { key: 'Bank Name', label: 'Bank Name', type: 'text', required: true },
      {
        key: 'Account Number',
        label: 'Account Number',
        type: 'text',
        required: true,
        sensitive: true,
      },
      { key: 'IFSC Code', label: 'IFSC / SWIFT Code', type: 'text' },
      {
        key: 'Account Type',
        label: 'Account Type',
        type: 'select',
        options: ['Savings', 'Current', 'Joint Savings', 'NRE', 'NRO', 'Fixed Deposit'],
      },
      { key: 'Branch', label: 'Branch', type: 'text' },
      { key: 'Nominee', label: 'Nominee', type: 'text' },
      { key: 'Net Banking ID', label: 'Net Banking User ID', type: 'text', sensitive: true },
    ],
  },
  {
    id: 'credit-debit-cards',
    label: 'Credit / Debit Cards',
    shortLabel: 'Cards',
    color: '#F0C38E',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Wallet',
    fields: [
      { key: 'Card Name', label: 'Card Name / Type', type: 'text', required: true },
      {
        key: 'Card Number (Last 4)',
        label: 'Last 4 Digits',
        type: 'text',
        required: true,
        sensitive: true,
      },
      {
        key: 'Card Network',
        label: 'Card Network',
        type: 'select',
        options: ['Visa', 'Mastercard', 'RuPay', 'Amex', 'Diners'],
      },
      { key: 'Expiry', label: 'Expiry (MM/YYYY)', type: 'text' },
      { key: 'Credit Limit', label: 'Credit Limit', type: 'text' },
      { key: 'Billing Cycle', label: 'Billing Cycle Date', type: 'text' },
      { key: 'Customer Care', label: 'Customer Care Number', type: 'tel' },
    ],
  },
  {
    id: 'institutional-docs',
    label: 'Institutional Documents',
    shortLabel: 'Institutional',
    color: '#A89FD4',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Building2',
    fields: [
      { key: 'Institution Name', label: 'Institution / Company', type: 'text', required: true },
      {
        key: 'Document Type',
        label: 'Document Type',
        type: 'select',
        options: [
          'Insurance Policy',
          'Loan Account',
          'Mutual Fund',
          'PPF Account',
          'School Certificate',
          'Degree Certificate',
          'Employment Letter',
          'Property Document',
          'Other',
        ],
      },
      {
        key: 'Reference Number',
        label: 'Policy / Reference Number',
        type: 'text',
        sensitive: true,
      },
      { key: 'Start Date', label: 'Start / Issue Date', type: 'date' },
      { key: 'End / Maturity Date', label: 'End / Maturity Date', type: 'date' },
      { key: 'Amount / Value', label: 'Amount / Sum', type: 'text' },
      { key: 'Contact Number', label: 'Contact / Agent Number', type: 'tel' },
    ],
  },
  {
    id: 'vehicle-documents',
    label: 'Vehicle Documents',
    shortLabel: 'Vehicles',
    color: '#5EC4B8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Car',
    fields: [
      { key: 'Vehicle Name', label: 'Vehicle Name / Model', type: 'text', required: true },
      { key: 'Registration Number', label: 'Registration Number', type: 'text', required: true },
      { key: 'Engine Number', label: 'Engine Number', type: 'text', sensitive: true },
      { key: 'Chassis Number', label: 'Chassis Number', type: 'text', sensitive: true },
      {
        key: 'Fuel Type',
        label: 'Fuel Type',
        type: 'select',
        options: ['Petrol', 'Diesel', 'CNG', 'Electric', 'Hybrid'],
      },
      { key: 'Insurance Expiry', label: 'Insurance Expiry', type: 'date' },
      { key: 'PUC Expiry', label: 'PUC / Emission Expiry', type: 'date' },
    ],
  },
  {
    id: 'family-profiles',
    label: 'Family Member Profiles',
    shortLabel: 'Profiles',
    color: '#D4A5E6',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Users',
    fields: [
      { key: 'Full Name', label: 'Full Name', type: 'text', required: true },
      { key: 'Relationship', label: 'Relationship', type: 'text' },
      { key: 'Date of Birth', label: 'Date of Birth', type: 'date' },
      {
        key: 'Blood Group',
        label: 'Blood Group',
        type: 'select',
        options: ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
      },
      { key: 'Emergency Contact', label: 'Emergency Contact', type: 'tel' },
      { key: 'Medical Conditions', label: 'Medical Conditions / Allergies', type: 'text' },
    ],
  },
  {
    id: 'passport',
    label: 'Passport',
    shortLabel: 'Passport',
    color: '#77B6EA',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'BookOpen',
    fields: [
      { key: 'Passport Number', label: 'Passport Number', type: 'text', required: true, sensitive: true },
      { key: 'Date of Issue', label: 'Date of Issue', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
      { key: 'Place of Issue', label: 'Place of Issue', type: 'text' },
      { key: 'File Number', label: 'File Number', type: 'text', sensitive: true },
    ],
  },
  {
    id: 'drivers-license',
    label: "Driver's License",
    shortLabel: 'License',
    color: '#8ED1C7',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'IdCard',
    fields: [
      { key: 'License Number', label: 'License Number', type: 'text', required: true, sensitive: true },
      { key: 'Date of Issue', label: 'Date of Issue', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
      { key: 'Issuing Authority', label: 'Issuing Authority', type: 'text' },
      { key: 'Vehicle Class', label: 'Vehicle Class', type: 'text' },
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    shortLabel: 'Insurance',
    color: '#6BB8CC',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Shield',
    fields: [
      { key: 'Provider', label: 'Provider', type: 'text', required: true },
      { key: 'Policy Number', label: 'Policy Number', type: 'text', required: true, sensitive: true },
      { key: 'Type', label: 'Type', type: 'select', options: ['Health', 'Life', 'Vehicle', 'Travel', 'Home', 'Other'] },
      { key: 'Start Date', label: 'Start Date', type: 'date' },
      { key: 'End Date', label: 'End Date / Expiry', type: 'date' },
      { key: 'Contact', label: 'Agent / Support Contact', type: 'tel' },
    ],
  },
  {
    id: 'visa',
    label: 'Visa',
    shortLabel: 'Visa',
    color: '#A89FD4',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Globe',
    fields: [
      { key: 'Country', label: 'Country', type: 'text', required: true },
      { key: 'Visa Type', label: 'Visa Type', type: 'text' },
      { key: 'Visa Number', label: 'Visa Number', type: 'text', sensitive: true },
      { key: 'Issue Date', label: 'Issue Date', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
    ],
  },
  {
    id: 'medical-record',
    label: 'Medical Record',
    shortLabel: 'Medical',
    color: '#F1AA9B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'BriefcaseMedical',
    fields: [
      { key: 'Hospital / Clinic', label: 'Hospital / Clinic', type: 'text' },
      { key: 'Doctor', label: 'Doctor', type: 'text' },
      { key: 'Record ID', label: 'Record ID', type: 'text', sensitive: true },
      { key: 'Date', label: 'Date', type: 'date' },
      { key: 'Notes', label: 'Notes', type: 'text' },
    ],
  },
  {
    id: 'certificate',
    label: 'Certificate',
    shortLabel: 'Cert',
    color: '#F0C38E',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'ScrollText',
    fields: [
      { key: 'Certificate Name', label: 'Certificate Name', type: 'text', required: true },
      { key: 'Issuer', label: 'Issuer', type: 'text' },
      { key: 'Certificate ID', label: 'Certificate ID', type: 'text', sensitive: true },
      { key: 'Issue Date', label: 'Issue Date', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
    ],
  },
  {
    id: 'contract',
    label: 'Contract',
    shortLabel: 'Contract',
    color: '#E8B347',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'FileText',
    fields: [
      { key: 'Party', label: 'Party / Vendor', type: 'text', required: true },
      { key: 'Contract ID', label: 'Contract ID', type: 'text', sensitive: true },
      { key: 'Start Date', label: 'Start Date', type: 'date' },
      { key: 'End Date', label: 'End Date', type: 'date' },
      { key: 'Notes', label: 'Notes', type: 'text' },
    ],
  },
  {
    id: 'warranty',
    label: 'Warranty',
    shortLabel: 'Warranty',
    color: '#5EC4B8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Wrench',
    fields: [
      { key: 'Product', label: 'Product', type: 'text', required: true },
      { key: 'Brand', label: 'Brand', type: 'text' },
      { key: 'Serial Number', label: 'Serial Number', type: 'text', sensitive: true },
      { key: 'Purchase Date', label: 'Purchase Date', type: 'date' },
      { key: 'Warranty Expiry', label: 'Warranty Expiry', type: 'date' },
    ],
  },
  {
    id: 'membership',
    label: 'Membership',
    shortLabel: 'Member',
    color: '#D4A5E6',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'User',
    fields: [
      { key: 'Organization', label: 'Organization', type: 'text', required: true },
      { key: 'Member ID', label: 'Member ID', type: 'text', sensitive: true },
      { key: 'Start Date', label: 'Start Date', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
    ],
  },
  {
    id: 'subscription',
    label: 'Subscription',
    shortLabel: 'Subs',
    color: '#8EB4E8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'RefreshCw',
    fields: [
      { key: 'Service', label: 'Service', type: 'text', required: true },
      { key: 'Plan', label: 'Plan', type: 'text' },
      { key: 'Billing Cycle', label: 'Billing Cycle', type: 'select', options: ['Monthly', 'Yearly', 'Weekly', 'Other'] },
      { key: 'Renewal Date', label: 'Renewal Date', type: 'date' },
      { key: 'Account Email', label: 'Account Email', type: 'text', sensitive: true },
    ],
  },
  {
    id: 'permit',
    label: 'Permit',
    shortLabel: 'Permit',
    color: '#F1AA9B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'BadgeCheck',
    fields: [
      { key: 'Permit Type', label: 'Permit Type', type: 'text', required: true },
      { key: 'Permit Number', label: 'Permit Number', type: 'text', sensitive: true },
      { key: 'Issue Date', label: 'Issue Date', type: 'date' },
      { key: 'Expiry Date', label: 'Expiry Date', type: 'date' },
      { key: 'Authority', label: 'Authority', type: 'text' },
    ],
  },
  {
    id: 'other',
    label: 'Other',
    shortLabel: 'Other',
    color: '#BFB4DF',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'File',
    fields: [{ key: 'Reference', label: 'Reference / ID', type: 'text', sensitive: true }],
  },
];

export function getCategoryById(id: CategoryId): CategoryConfig | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
