import { CategoryId } from './storage';

export interface CategoryConfig {
  id: CategoryId;
  label: string;
  shortLabel: string;
  color: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
  lightBg: string;
  icon: string;
  fields: FieldConfig[];
}

/**
 * input masking / formatting hint consumed by DocumentFormModal.
 * - 'date-dmy'      →  DD-MM-YYYY
 * - 'card-number'   →  xxxx-xxxx-xxxx-xxxx
 * - 'expiry-mmyyyy' →  MM/YYYY
 * - 'account-number'→  spaces every 4 digits
 * - 'phone'         →  +XX XXXXX-XXXXX
 * - 'ifsc'          →  upper-case, XXXX0XXXXXX pattern hint
 * - 'aadhaar'       →  XXXX XXXX XXXX
 * - 'pan'           →  AAAAA9999A
 * - 'alpha-upper'   →  convert to upper-case
 * - 'email'         →  name@domain.tld
 * - 'url'           →  https://… or domain.tld
 * - 'login-id'      →  username or email
 */
export type FieldFormat =
  | 'date-dmy'
  | 'card-number'
  | 'expiry-mmyyyy'
  | 'account-number'
  | 'phone'
  | 'ifsc'
  | 'aadhaar'
  | 'pan'
  | 'alpha-upper'
  | 'email'
  | 'url'
  | 'login-id';

export interface FieldConfig {
  key: string;
  label: string;
  type: 'text' | 'date' | 'number' | 'select' | 'tel';
  required?: boolean;
  options?: string[];
  placeholder?: string;
  sensitive?: boolean;
  /** Masking / auto-format applied in the document form input. */
  format?: FieldFormat;
}

export const CATEGORIES: CategoryConfig[] = [
  {
    id: 'password-vault',
    label: 'Passwords',
    shortLabel: 'Passwords',
    color: '#E8B347',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'KeyRound',
    fields: [
      {
        key: 'Website / App',
        label: 'Website / App',
        type: 'text',
        required: true,
        placeholder: 'e.g. Gmail, Instagram, HDFC NetBanking',
      },
      {
        key: 'Login URL',
        label: 'Login URL',
        type: 'text',
        format: 'url',
        placeholder: 'e.g. https://accounts.google.com',
      },
      {
        key: 'User ID / Email',
        label: 'User ID / Email',
        type: 'text',
        required: true,
        sensitive: true,
        format: 'login-id',
        placeholder: 'e.g. name@example.com',
      },
      {
        key: 'Password',
        label: 'Password',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'Saved securely in your vault',
      },
      {
        key: '2FA / Recovery',
        label: '2FA / Recovery notes',
        type: 'text',
        sensitive: true,
        placeholder: 'e.g. backup codes location',
      },
    ],
  },
  {
    id: 'government-ids',
    label: 'Government IDs',
    shortLabel: 'Gov IDs',
    color: '#F1AA9B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'CreditCard',
    fields: [
      {
        key: 'Document Type',
        label: 'Document Type',
        type: 'select',
        required: true,
        options: [
          'Aadhaar Card',
          'PAN Card',
          'Passport',
          'Voter ID',
          'Driving License',
          'Birth Certificate',
          'Other',
        ],
      },
      {
        key: 'ID / Document Number',
        label: 'ID / Document Number',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'e.g. XXXX XXXX XXXX or AAAAA9999A',
      },
      {
        key: 'Date of Issue',
        label: 'Date of Issue',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Issuing Authority', label: 'Issuing Authority', type: 'text' },
      { key: 'Address on Document', label: 'Address on Document', type: 'text' },
    ],
  },
  {
    id: 'bank-accounts',
    label: 'Bank Accounts',
    shortLabel: 'Bank',
    color: '#8EB4E8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Landmark',
    fields: [
      { key: 'Bank Name', label: 'Bank Name', type: 'text', required: true },
      {
        key: 'Account Number',
        label: 'Account Number',
        type: 'text',
        required: true,
        sensitive: true,
        format: 'account-number',
        placeholder: 'XXXX XXXX XXXX XXXX',
      },
      {
        key: 'IFSC Code',
        label: 'IFSC Code',
        type: 'text',
        format: 'ifsc',
        placeholder: 'e.g. SBIN0001234',
      },
      {
        key: 'Account Type',
        label: 'Account Type',
        type: 'select',
        options: ['Savings', 'Current', 'Joint Savings', 'NRE', 'NRO'],
      },
      { key: 'Branch', label: 'Branch', type: 'text' },
      { key: 'Nominee', label: 'Nominee', type: 'text' },
      {
        key: 'Linked Phone',
        label: 'Linked Phone Number',
        type: 'tel',
        format: 'phone',
        placeholder: '+91 …',
      },
      { key: 'Net Banking ID', label: 'Net Banking User ID', type: 'text', sensitive: true },
    ],
  },
  {
    id: 'credit-debit-cards',
    label: 'Credit / Debit Cards',
    shortLabel: 'Cards',
    color: '#F0C38E',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Wallet',
    fields: [
      { key: 'Card Name', label: 'Card Name / Type', type: 'text', required: true },
      {
        key: 'Card Number (Last 4)',
        label: 'Card Number',
        type: 'text',
        required: true,
        sensitive: true,
        format: 'card-number',
        placeholder: 'xxxx-xxxx-xxxx-xxxx',
      },
      {
        key: 'Card Network',
        label: 'Card Network',
        type: 'select',
        options: ['Visa', 'Mastercard', 'RuPay', 'Amex', 'Diners'],
      },
      {
        key: 'Expiry',
        label: 'Expiry (MM/YYYY)',
        type: 'text',
        format: 'expiry-mmyyyy',
        placeholder: 'MM/YYYY',
      },
      { key: 'Credit Limit', label: 'Credit Limit', type: 'text' },
      {
        key: 'Billing Cycle',
        label: 'Billing Cycle Date',
        type: 'text',
        placeholder: 'e.g. 5th of every month',
      },
      { key: 'Customer Care', label: 'Customer Care Number', type: 'tel', format: 'phone' },
    ],
  },
  {
    id: 'institutional-docs',
    label: 'Institutional Documents',
    shortLabel: 'Institutional',
    color: '#A89FD4',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Building2',
    fields: [
      { key: 'Institution Name', label: 'Institution / Company', type: 'text', required: true },
      {
        key: 'Document Type',
        label: 'Document Type',
        type: 'select',
        options: [
          'Insurance Policy',
          'Loan Account',
          'Mutual Fund',
          'PPF Account',
          'School Certificate',
          'Degree Certificate',
          'Employment Letter',
          'Property Document',
          'Other',
        ],
      },
      {
        key: 'Reference Number',
        label: 'Policy / Reference Number',
        type: 'text',
        sensitive: true,
      },
      {
        key: 'Start Date',
        label: 'Start / Issue Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'End / Maturity Date',
        label: 'End / Maturity Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Amount / Value', label: 'Amount / Sum', type: 'text' },
      { key: 'Contact Number', label: 'Contact / Agent Number', type: 'tel', format: 'phone' },
    ],
  },
  {
    id: 'vehicle-documents',
    label: 'Vehicle Documents',
    shortLabel: 'Vehicles',
    color: '#5EC4B8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Car',
    fields: [
      { key: 'Vehicle Name', label: 'Vehicle Name / Model', type: 'text', required: true },
      { key: 'Registration Number', label: 'Registration Number', type: 'text', required: true },
      { key: 'Engine Number', label: 'Engine Number', type: 'text', sensitive: true },
      { key: 'Chassis Number', label: 'Chassis Number', type: 'text', sensitive: true },
      {
        key: 'Fuel Type',
        label: 'Fuel Type',
        type: 'select',
        options: ['Petrol', 'Diesel', 'CNG', 'Electric', 'Hybrid'],
      },
      {
        key: 'Insurance Expiry',
        label: 'Insurance Expiry',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'PUC Expiry',
        label: 'PUC / Emission Expiry',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
    ],
  },
  {
    id: 'family-profiles',
    label: 'Family Member Profiles',
    shortLabel: 'Profiles',
    color: '#D4A5E6',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Users',
    fields: [
      { key: 'Full Name', label: 'Full Name', type: 'text', required: true },
      { key: 'Relationship', label: 'Relationship', type: 'text' },
      {
        key: 'Date of Birth',
        label: 'Date of Birth',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Blood Group',
        label: 'Blood Group',
        type: 'select',
        options: ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
      },
      { key: 'Emergency Contact', label: 'Emergency Contact', type: 'tel', format: 'phone' },
      { key: 'Medical Conditions', label: 'Medical Conditions / Allergies', type: 'text' },
    ],
  },
  {
    id: 'passport',
    label: 'Passport',
    shortLabel: 'Passport',
    color: '#77B6EA',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'BookOpen',
    fields: [
      {
        key: 'Passport Number',
        label: 'Passport Number',
        type: 'text',
        required: true,
        sensitive: true,
      },
      {
        key: 'Date of Issue',
        label: 'Date of Issue',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Place of Issue', label: 'Place of Issue', type: 'text' },
      { key: 'File Number', label: 'File Number', type: 'text', sensitive: true },
    ],
  },
  {
    id: 'drivers-license',
    label: 'Driver\u2019s License',
    shortLabel: 'License',
    color: '#8ED1C7',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'IdCard',
    fields: [
      {
        key: 'License Number',
        label: 'License Number',
        type: 'text',
        required: true,
        sensitive: true,
      },
      {
        key: 'Date of Issue',
        label: 'Date of Issue',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Issuing Authority', label: 'Issuing Authority', type: 'text' },
      { key: 'Vehicle Class', label: 'Vehicle Class', type: 'text' },
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    shortLabel: 'Insurance',
    color: '#6BB8CC',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Shield',
    fields: [
      { key: 'Provider', label: 'Provider', type: 'text', required: true },
      {
        key: 'Policy Number',
        label: 'Policy Number',
        type: 'text',
        required: true,
        sensitive: true,
      },
      {
        key: 'Type',
        label: 'Type',
        type: 'select',
        options: ['Life', 'Health', 'Vehicle', 'Home', 'Travel', 'Other'],
      },
      { key: 'Premium Amount', label: 'Premium Amount', type: 'text' },
      {
        key: 'Premium Frequency',
        label: 'Premium Frequency',
        type: 'select',
        options: ['Monthly', 'Quarterly', 'Half-yearly', 'Annual'],
      },
      { key: 'Sum Insured', label: 'Sum Insured', type: 'text' },
      { key: 'Nominee', label: 'Nominee', type: 'text' },
      {
        key: 'Start Date',
        label: 'Start Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'End Date',
        label: 'End Date / Expiry',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Contact', label: 'Agent / Support Contact', type: 'tel', format: 'phone' },
    ],
  },
  {
    id: 'investment',
    label: 'Investments',
    shortLabel: 'Invest',
    color: '#7BC4A0',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'TrendingUp',
    fields: [
      {
        key: 'Type',
        label: 'Type',
        type: 'select',
        required: true,
        options: ['FD', 'RD', 'Mutual Fund', 'PPF', 'NPS', 'Stocks', 'Gold', 'Other'],
      },
      { key: 'Institution', label: 'Institution', type: 'text', required: true },
      {
        key: 'Account / Folio Number',
        label: 'Account / Folio Number',
        type: 'text',
        sensitive: true,
      },
      { key: 'Invested Amount', label: 'Invested Amount', type: 'text' },
      { key: 'Current Value', label: 'Current Value', type: 'text' },
      {
        key: 'Maturity Date',
        label: 'Maturity Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Nominee', label: 'Nominee', type: 'text' },
    ],
  },
  {
    id: 'loan',
    label: 'Loans / EMI',
    shortLabel: 'Loans',
    color: '#E8A07A',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Banknote',
    fields: [
      { key: 'Lender', label: 'Lender', type: 'text', required: true },
      {
        key: 'Loan Type',
        label: 'Loan Type',
        type: 'select',
        options: ['Home', 'Personal', 'Vehicle', 'Education', 'Other'],
      },
      {
        key: 'Loan Account Number',
        label: 'Loan Account Number',
        type: 'text',
        sensitive: true,
      },
      { key: 'Principal', label: 'Principal', type: 'text' },
      { key: 'EMI Amount', label: 'EMI Amount', type: 'text' },
      { key: 'Interest Rate', label: 'Interest Rate (%)', type: 'text' },
      {
        key: 'Start Date',
        label: 'Start Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'End Date',
        label: 'End Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Remaining Tenure', label: 'Remaining Tenure', type: 'text', placeholder: 'e.g. 48 months' },
    ],
  },
  {
    id: 'income',
    label: 'Income / Expenses',
    shortLabel: 'Income',
    color: '#9BC47B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'CircleDollarSign',
    fields: [
      {
        key: 'Type',
        label: 'Type',
        type: 'select',
        required: true,
        options: ['Salary', 'Business', 'Rental', 'Pension', 'Expense', 'Other'],
      },
      { key: 'Source / Payee', label: 'Source / Payee', type: 'text', required: true },
      { key: 'Amount', label: 'Amount', type: 'text' },
      {
        key: 'Frequency',
        label: 'Frequency',
        type: 'select',
        options: ['One-time', 'Monthly', 'Quarterly', 'Annual'],
      },
      {
        key: 'Date',
        label: 'Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Linked Account', label: 'Linked Account / Notes', type: 'text' },
    ],
  },
  {
    id: 'visa',
    label: 'Visa',
    shortLabel: 'Visa',
    color: '#A89FD4',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Globe',
    fields: [
      { key: 'Country', label: 'Country', type: 'text', required: true },
      { key: 'Visa Type', label: 'Visa Type', type: 'text' },
      { key: 'Visa Number', label: 'Visa Number', type: 'text', sensitive: true },
      {
        key: 'Issue Date',
        label: 'Issue Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
    ],
  },
  {
    id: 'medical-record',
    label: 'Medical Record',
    shortLabel: 'Medical',
    color: '#F1AA9B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'BriefcaseMedical',
    fields: [
      { key: 'Hospital / Clinic', label: 'Hospital / Clinic', type: 'text' },
      { key: 'Doctor', label: 'Doctor', type: 'text' },
      { key: 'Record ID', label: 'Record ID', type: 'text', sensitive: true },
      { key: 'Date', label: 'Date', type: 'text', format: 'date-dmy', placeholder: 'DD-MM-YYYY' },
      { key: 'Notes', label: 'Notes', type: 'text' },
    ],
  },
  {
    id: 'certificate',
    label: 'Certificate',
    shortLabel: 'Certificates',
    color: '#F0C38E',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'ScrollText',
    fields: [
      { key: 'Certificate Name', label: 'Certificate Name', type: 'text', required: true },
      { key: 'Issuer', label: 'Issuer', type: 'text' },
      { key: 'Certificate ID', label: 'Certificate ID', type: 'text', sensitive: true },
      {
        key: 'Issue Date',
        label: 'Issue Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
    ],
  },
  {
    id: 'contract',
    label: 'Contract',
    shortLabel: 'Contract',
    color: '#E8B347',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'FileText',
    fields: [
      { key: 'Party', label: 'Party / Vendor', type: 'text', required: true },
      { key: 'Contract ID', label: 'Contract ID', type: 'text', sensitive: true },
      {
        key: 'Start Date',
        label: 'Start Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'End Date',
        label: 'End Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Notes', label: 'Notes', type: 'text' },
    ],
  },
  {
    id: 'warranty',
    label: 'Warranty',
    shortLabel: 'Warranty',
    color: '#5EC4B8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'Wrench',
    fields: [
      { key: 'Product', label: 'Product', type: 'text', required: true },
      { key: 'Brand', label: 'Brand', type: 'text' },
      { key: 'Serial Number', label: 'Serial Number', type: 'text', sensitive: true },
      {
        key: 'Purchase Date',
        label: 'Purchase Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Warranty Expiry',
        label: 'Warranty Expiry',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
    ],
  },
  {
    id: 'membership',
    label: 'Membership',
    shortLabel: 'Member',
    color: '#D4A5E6',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'User',
    fields: [
      { key: 'Organization', label: 'Organization', type: 'text', required: true },
      { key: 'Member ID', label: 'Member ID', type: 'text', sensitive: true },
      {
        key: 'Start Date',
        label: 'Start Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
    ],
  },
  {
    id: 'subscription',
    label: 'Subscription',
    shortLabel: 'Subscriptions',
    color: '#8EB4E8',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'RefreshCw',
    fields: [
      { key: 'Service', label: 'Service', type: 'text', required: true },
      { key: 'Plan', label: 'Plan', type: 'text' },
      {
        key: 'Billing Cycle',
        label: 'Billing Cycle',
        type: 'select',
        options: ['Monthly', 'Yearly', 'Weekly', 'Other'],
      },
      {
        key: 'Renewal Date',
        label: 'Renewal Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Account Email',
        label: 'Account Email',
        type: 'text',
        sensitive: true,
        format: 'email',
        placeholder: 'e.g. name@example.com',
      },
    ],
  },
  {
    id: 'permit',
    label: 'Permit',
    shortLabel: 'Permit',
    color: '#F1AA9B',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'BadgeCheck',
    fields: [
      { key: 'Permit Type', label: 'Permit Type', type: 'text', required: true },
      { key: 'Permit Number', label: 'Permit Number', type: 'text', sensitive: true },
      {
        key: 'Issue Date',
        label: 'Issue Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      {
        key: 'Expiry Date',
        label: 'Expiry Date',
        type: 'text',
        format: 'date-dmy',
        placeholder: 'DD-MM-YYYY',
      },
      { key: 'Authority', label: 'Authority', type: 'text' },
    ],
  },
  {
    id: 'other',
    label: 'Other',
    shortLabel: 'Other',
    color: '#BFB4DF',
    bgColor: 'bg-vault-elevated',
    borderColor: 'border-border',
    textColor: 'text-vault-muted',
    lightBg: 'bg-vault-panel',
    icon: 'File',
    fields: [{ key: 'Reference', label: 'Reference / ID', type: 'text', sensitive: true }],
  },
];

export function getCategoryById(id: CategoryId): CategoryConfig | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
