version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      nextjs:
        patterns:
          - "next"
          - "eslint-config-next"
      lint-format:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
          - "autoprefixer"

